mixed-port: 7890
allow-lan: true
mode: rule
log-level: info

proxies:
  - name: Trojan1
    type: trojan
    server: trojan1.sh-crystalcg.com
    port: 60505
    password: '123456'
    udp: true
    skip-cert-verify: true

  - name: Trojan2
    type: trojan
    server: trojan.sh-crystalcg.com
    port: 60605
    password: '123456'
    udp: true
    skip-cert-verify: true

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - Trojan1
      - Trojan2
      - DIRECT

rules:
  - DOMAIN-SUFFIX,google.com,PROXY
  - DOMAIN-SUFFIX,github.com,PROXY
  - MATCH,DIRECT
